---
- name: stop and disable a service
  service:
    name: systemd-resolved 
    state: stopped
    enabled: false

- name: Remove resolv.conf symlink 
  file:
   path: "/etc/resolv.conf"
   state: absent
  notify: reload dnsmasq 

- name: Add resolv.conf config
  ansible.builtin.template:
    src: templates/resolv.conf.j2
    dest: "/etc/resolv.conf"
  notify: reload dnsmasq 

- name: Add dnsmasq config
  ansible.builtin.template:
    src: templates/dnsmasq.conf.j2
    dest: "/etc/dnsmasq.conf"
  notify: reload dnsmasq 

- name: Install Dnsmasq
  ansible.builtin.apt:
    name: dnsmasq
    state: present
  notify: reload dnsmasq 
      
